### ISSUE TITLE
Orphanet redundant double mining one text string

### ISSUE THREAD

**Issue by WariRay** [tudorgroza/fast_hpo_cr#2]
We did some quick tests with "Syngnathia-multiple anomalies syndrome" as the input. The results gives us two ORPHA codes:
[0:38]  ORPHA:3262      Syngnathia-multiple anomalies syndrome  Syngnathia-multiple anomalies syndrome
[20:38] ORPHA:93890     Malformation syndrome   anomalies syndrome

The results shows that we have 2 concepts mined from the same string using the input shown above. However, the second concept is redundant because it is just a higher diagnosis category in same tree. How do we disregard 2nd mined concept in same string?

For example, "93890 Orpha code: Rare developmental defect during embryogenesis". This provides no extra detail in this content.

**Comment by tudorgroza** [comment]
use `longestMatch=True` when calling `annotate` on an `HPOAnnotator` object.

**Comment by WariRay** [comment]
This works! Thanks!
